FILENAMELEN = 28
BLOCKSUMMARY = 8
ACTUALBLOCKSIZE = 1024
BLOCKSIZE = ACTUALBLOCKSIZE - BLOCKSUMMARY
DISKSIZE  = 1024 * BLOCKSIZE  # a 1MB disk
SEGMENTSIZE = 256  # blocks
NUMSEGMENTS = DISKSIZE / (BLOCKSIZE * SEGMENTSIZE)

INDIRECTBLOCKOFFSET = 1729 #http://en.wikipedia.org/wiki/1729_%28number%29 This is greater than any valid offset in an inode
INODEIDENTIFIEROFFSET = 1634 #NarcissisticNumber
NUMDIRECTBLOCKS = 1 # can have as many as 250 and still fit an Inode in a 1024 byte block
MAXDATABLOCKSINODE = (NUMDIRECTBLOCKS + BLOCKSIZE/4)